### ISSUE TITLE
No module named deformation

### ISSUE THREAD

**Issue by fabioo29** [verlab/ShapeAwareHumanRetargeting_IJCV_2021#1]
Obrigado por deixarem isto open-source! 

Estava a testar o codigo e diz que não tenho o package "deformation"... Instalei o package SWIG e segui os passos do README.md da pasta deformation e pareceu que correu tudo bem.

Estou a utilizar o Ubuntu 16. Alguma ideia do que poderá ser?

*EDIT #1*: Também não consegui encontrar versão do package "csaps" para a versão de python do projeto (2.7)

**Comment by RafaelAZV** [comment]
Olá @Fabioo29, vou dar uma olhada no que pode ser. Vamos disponibilizar containers do Singularity e Docker para facilitar o uso dos componentes principais do projeto em breve também.

**Comment by fabioo29** [comment]
Eu não consegui colocar para funcionar no Docker portanto são boas noticias. Obrigado!

**Comment by RafaelAZV** [comment]
Olá @Fabioo29. Para conseguir importar o módulo, você deve adicioná-lo ao PYTHONPATH, fazendo com que o python encontre o caminho correto. Para isso, você pode fazer da seguinte forma:
`export PYTHONPATH=$PYTHONPATH:<path_to_deformation_folder>`

Para evitar de utilizar este comando sempre, você pode adicioná-lo nas linhas finais do arquivo `~/.bashrc`. Este mesmo procedimento deverá ser feito no módulo `normal` também.

**Comment by fabioo29** [comment]
@RafaelAZV Obrigado pela resposta! Vou testar

E em relação ao package "csaps". É possivel instalar ele com Python 2.7? Só encontrei para Python 3.6...

**Comment by RafaelAZV** [comment]
Oi @Fabioo29. Fizemos um update na pasta `retargeting` contendo instruções atualizadas sobre o setup deste módulo que solucionam este problema.
